spring.application.name=TrackWise

# PostgreSQL Datasource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true

# Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

# News API
news.api.key=${NEWS_API_KEY}

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google AI
google.api.key=${GOOGLE_API_KEY}
google.cloud.project-id=${GOOGLE_CLOUD_PROJECT_ID}

# JWT
jwt.secret=${JWT_SECRET}

# Expose the health, info, and metrics endpoints over HTTP
management.endpoints.web.exposure.include=health,info,metrics